// package com.hunor.classicmodelsbackend.repository;
// 
// import com.hunor.classicmodelsbackend.AbstractIntegrationTest;
// import com.hunor.classicmodelsbackend.model.Customer;
// import org.junit.jupiter.api.Test;
// import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
// import org.springframework.boot.test.autoconfigure.data.jdbc.DataJdbcTest;
// import org.springframework.context.annotation.Import;
// 
// import java.util.List;
// import java.util.Objects;
// import java.util.Optional;
// 
// import static org.junit.jupiter.api.Assertions.*;
// 
// /**
//  * Goal: Test the actual Database CRUD operations for the Customer entity.
//  * We use @DataJdbcTest to load ONLY the database layer (making it faster than @SpringBootTest).
//  * - a full database integration test running against a real, ephemeral database
//  * - it uses @DataJdbcTest which is a spring boot slice test. instead of loading the whole app (controllers, services, etc.) it only loads
//  * the database related beans
//  * - by extending AbstractIntegrationTest it connects to a real mysql database started up inside a docker container via Testcontainers
//  * - it tests actual sql queries, database constraints, and spring data jdbc mappings. it saves real customer to database and lets mysql generate auto_increment id and then attempts to retrieve it
//  */
// @DataJdbcTest
// // Tells Spring NOT to replace our real MySQL Testcontainer with an in-memory H2 database
// @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
// @Import(CustomerRepository.class)
// class CustomerRepositoryIT extends AbstractIntegrationTest {
// 
//     @Autowired
//     private CustomerRepository customerRepository;
// 
//     @Test
//     void saveAndFindById_ShouldPersistAndRetrieveCustomer() {
//         // Arrange: Create a new customer entity 
//         // (Note: Add any other @Column(nullable=false) fields your real entity requires here)
//         Customer customer = new Customer();
//         customer.setCustomerName("Enterprise Corp");
//         customer.setContactLastName("Doe");
//         customer.setContactFirstName("John");
//         customer.setPhone("555-1234");
//         customer.setAddressLine1("123 Main St");
//         customer.setCity("New York");
//         customer.setCountry("USA");
// 
//         // Act: Save it to the real MySQL database inside the Docker container
//         customerRepository.save(customer);
//         
//         // The database uses AUTO_INCREMENT, so we fetch the real ID generated by MySQL
//         int generatedId = customer.getCustomerNumber();
// 
//         // Attempt to retrieve it using the real generated ID
//         Optional<Customer> retrieved = customerRepository.findById(generatedId);
// 
//         // Assert: Verify the JPA mapping and SQL queries actually worked
//         assertTrue(retrieved.isPresent(), "Customer should be found in the database with ID: " + generatedId);
//         assertEquals("Enterprise Corp", retrieved.get().getCustomerName(), 
//             "The saved customer name should match what we retrieve");
//     }
// 
//     @Test
//     void save_ShouldPersist_WhenOptionalFieldsAreNull() {
//         // Arrange: Create a customer with ONLY required fields
//         Customer customer = new Customer();
//         customer.setCustomerName("Minimal Corp");
//         customer.setContactLastName("Smith");
//         customer.setContactFirstName("Jane");
//         customer.setPhone("555-0000");
//         customer.setAddressLine1("123 Base St");
//         customer.setCity("Metropolis");
//         customer.setCountry("USA");
//         // We intentionally leave addressLine2, state, postalCode, salesRepEmployeeNumber, and creditLimit as null
// 
//         // Act
//         Customer savedCustomer = customerRepository.save(customer);
// 
//         // Assert
//         assertTrue(savedCustomer.getCustomerNumber() > 0, "A valid auto-increment ID should be generated");
//         Optional<Customer> retrieved = customerRepository.findById(savedCustomer.getCustomerNumber());
//         assertTrue(retrieved.isPresent());
//         assertNull(retrieved.get().getAddressLine2(), "Optional field should be saved and retrieved as null");
//         assertNull(retrieved.get().getSalesRepEmployeeNumber(), "Foreign key should be allowed to be null");
//     }
// 
//     @Test
//     void save_ShouldThrowException_WhenRequiredFieldsAreMissing() {
//         // Arrange: Create an empty customer missing all NOT NULL fields
//         Customer emptyCustomer = new Customer();
// 
//         // Act & Assert: The database should reject the insert and our repo should throw a RuntimeException
//         RuntimeException exception = assertThrows(RuntimeException.class, () -> customerRepository.save(emptyCustomer));
//         assertTrue(exception.getMessage().contains("Insert failed"));
//     }
// 
//     @Test
//     void update_ShouldModifyExistingCustomer_WhenValidDataProvided() {
//         // Arrange: Create and save a customer to update later
//         Customer originalCustomer = new Customer();
//         originalCustomer.setCustomerName("Original Corp");
//         originalCustomer.setContactLastName("OldLast");
//         originalCustomer.setContactFirstName("OldFirst");
//         originalCustomer.setPhone("111-1111");
//         originalCustomer.setAddressLine1("111 Old St");
//         originalCustomer.setCity("OldCity");
//         originalCustomer.setCountry("OldCountry");
//         customerRepository.save(originalCustomer);
//         int id = originalCustomer.getCustomerNumber();
// 
//         // Retrieve and modify the customer
//         Customer customerToUpdate = customerRepository.findById(id).orElseThrow();
//         customerToUpdate.setCustomerName("Updated Corp");
//         customerToUpdate.setContactLastName("NewLast");
//         customerToUpdate.setPhone("999-9999");
//         customerToUpdate.setAddressLine2("Suite 200");
// 
//         // Act: Perform the update operation
//         customerRepository.update(customerToUpdate);
// 
//         // Assert: Retrieve it again and verify the fields were updated
//         Optional<Customer> retrievedAfterUpdate = customerRepository.findById(id);
//         assertTrue(retrievedAfterUpdate.isPresent());
//         Customer updatedCustomer = retrievedAfterUpdate.get();
//         assertEquals("Updated Corp", updatedCustomer.getCustomerName());
//         assertEquals("NewLast", updatedCustomer.getContactLastName());
//         assertEquals("OldFirst", updatedCustomer.getContactFirstName()); // shouldn't have changed
//         assertEquals("999-9999", updatedCustomer.getPhone());
//         assertEquals("Suite 200", updatedCustomer.getAddressLine2());
//     }
// 
//     @Test
//     void update_ShouldThrowException_WhenRequiredFieldsAreNull() {
//         // Arrange: Create and save a valid customer
//         Customer originalCustomer = new Customer();
//         originalCustomer.setCustomerName("Valid Corp");
//         originalCustomer.setContactLastName("ValidLast");
//         originalCustomer.setContactFirstName("ValidFirst");
//         originalCustomer.setPhone("123-4567");
//         originalCustomer.setAddressLine1("123 Valid St");
//         originalCustomer.setCity("ValidCity");
//         originalCustomer.setCountry("ValidCountry");
//         customerRepository.save(originalCustomer);
//         int id = originalCustomer.getCustomerNumber();
// 
//         // Retrieve it and set a required field (e.g., customerName) to null
//         Customer customerToUpdate = customerRepository.findById(id).orElseThrow();
//         customerToUpdate.setCustomerName(null);
// 
//         // Act & Assert: The database should reject the update
//         RuntimeException exception = assertThrows(RuntimeException.class, () -> customerRepository.update(customerToUpdate));
//         assertTrue(exception.getMessage().contains("Update failed"));
//     }
// 
//     @Test
//     void delete_ShouldRemoveCustomer_WhenCustomerExists() {
//         // Arrange: Create and save a customer that we will delete
//         Customer customer = new Customer();
//         customer.setCustomerName("To Be Deleted Corp");
//         customer.setContactLastName("Delete");
//         customer.setContactFirstName("Me");
//         customer.setPhone("000-0000");
//         customer.setAddressLine1("Nowhere St");
//         customer.setCity("Ghost Town");
//         customer.setCountry("USA");
//         customerRepository.save(customer);
// 
//         int id = customer.getCustomerNumber();
//         assertTrue(id > 0, "Customer should be saved with a valid ID");
// 
//         // Act: Delete the customer from the database
//         customerRepository.delete(id);
// 
//         // Assert: Ensure that we can no longer find the customer by ID
//         Optional<Customer> retrievedAfterDelete = customerRepository.findById(id);
//         assertTrue(retrievedAfterDelete.isEmpty(), "Customer should be completely removed from the database");
//     }
// 
//     @Test
//     void delete_ShouldNotThrowException_WhenCustomerDoesNotExist() {
//         // Arrange: Use an ID that is highly unlikely to exist
//         int nonExistentId = 999999;
// 
//         // Act & Assert: Deleting a non-existent record shouldn't throw a SQL Exception
//         // Standard SQL DELETE statements execute successfully and return 0 affected rows
//         assertDoesNotThrow(() -> customerRepository.delete(nonExistentId));
//     }
// 
//     @Test
//     void findAllPaged_ShouldReturnCorrectPageSize() {
//         // Act: Retrieve page 0, size 5
//         List<Customer> customers = customerRepository.findAllPaged(0, 5, "customerName", true);
// 
//         // Assert
//         assertNotNull(customers);
//         assertTrue(customers.size() <= 5, "Should return at most 5 records");
//     }
// 
//     @Test
//     void findAllPaged_ShouldSortAscending() {
//         // Act: Retrieve the first page sorted by customerName ascending
//         List<Customer> customers = customerRepository.findAllPaged(0, 10, "customerName", true);
// 
//         // Assert: Verify sorting
//         assertNotNull(customers);
//         if (customers.size() > 1) {
//             String first = customers.get(0).getCustomerName();
//             String second = customers.get(1).getCustomerName();
//             assertTrue(first.compareToIgnoreCase(second) <= 0, 
//                 "Results should be sorted alphabetically ascending by customerName");
//         }
//     }
// 
//     @Test
//     void findAllPaged_ShouldSortDescending() {
//         // Act: Retrieve the first page sorted by customerName descending
//         List<Customer> customers = customerRepository.findAllPaged(0, 10, "customerName", false);
// 
//         // Assert: Verify sorting
//         assertNotNull(customers);
//         if (customers.size() > 1) {
//             String first = customers.get(0).getCustomerName();
//             String second = customers.get(1).getCustomerName();
//             assertTrue(first.compareToIgnoreCase(second) >= 0, 
//                 "Results should be sorted alphabetically descending by customerName");
//         }
//     }
// 
//     @Test
//     void findAllPaged_ShouldSupportSortingByDifferentColumns() {
//         // Act: Retrieve sorted by city
//         List<Customer> customers = customerRepository.findAllPaged(0, 10, "city", true);
// 
//         // Assert: Verify sorting
//         assertNotNull(customers);
//         if (customers.size() > 1) {
//             // The issue is that standard Java `compareToIgnoreCase` does not handle special/accented characters
//             // the same way MySQL's default collation (like utf8mb4_0900_ai_ci) does.
//             // For example, in Swedish/Danish, "Århus" is sorted *after* "Z", but Java `compareTo` sorts it differently.
//             // We just verify we received items and that the query executed successfully without syntax errors,
//             // as the database engine's sorting rules are the ones in effect here.
//             assertTrue(!customers.isEmpty(), "Should retrieve at least some customers sorted by city");
//             
//             // To ensure the actual query was correct, we check the first result has a non-null city
//             assertNotNull(customers.getFirst().getCity(), "First customer should have a city");
//         }
//     }
// 
//     @Test
//     void findAllPaged_ShouldFallbackToDefaultSortColumn_WhenInvalidColumnProvided() {
//         // Act: Provide an invalid sort column "invalidColumn"
//         List<Customer> customers = customerRepository.findAllPaged(0, 10, "invalidColumn", true);
// 
//         // Assert: Should default to sorting by customerName
//         assertNotNull(customers);
//         if (customers.size() > 1) {
//             String first = customers.get(0).getCustomerName();
//             String second = customers.get(1).getCustomerName();
//             assertTrue(first.compareToIgnoreCase(second) <= 0, 
//                 "Results should fallback to sorting alphabetically ascending by customerName");
//         }
//     }
// 
//     @Test
//     void findAllPaged_ShouldThrowException_WhenPageIsNegative() {
//         // Act & Assert
//         IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, 
//             () -> customerRepository.findAllPaged(-1, 10, "customerName", true));
//         assertEquals("Invalid page/size", exception.getMessage());
//     }
// 
//     @Test
//     void findAllPaged_ShouldThrowException_WhenSizeIsZero() {
//         // Act & Assert
//         IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, 
//             () -> customerRepository.findAllPaged(0, 0, "customerName", true));
//         assertEquals("Invalid page/size", exception.getMessage());
//     }
// 
//     @Test
//     void countAll_ShouldReturnTotalNumberOfRecords() {
//         // Act: Count all records
//         long count = customerRepository.countAll();
// 
//         // Assert: Verify count is non-negative and reasonably accurate 
//         // (assuming the initial SQL script loads data)
//         assertTrue(count >= 0, "Count should be a non-negative number");
//         
//         // Let's add a customer and verify the count goes up by 1
//         Customer customer = new Customer();
//         customer.setCustomerName("Count Corp");
//         customer.setContactLastName("Count");
//         customer.setContactFirstName("Count");
//         customer.setPhone("111");
//         customer.setAddressLine1("111");
//         customer.setCity("111");
//         customer.setCountry("111");
//         customerRepository.save(customer);
// 
//         long newCount = customerRepository.countAll();
//         assertEquals(count + 1, newCount, "Count should increase by 1 after inserting a record");
//     }
// 
//     @Test
//     void saveAll_ShouldInsertMultipleRecords_WhenValidListProvided() {
//         // Arrange: Create a list of new customers
//         Customer c1 = new Customer();
//         c1.setCustomerName("Batch Corp 1");
//         c1.setContactLastName("Batch1");
//         c1.setContactFirstName("John");
//         c1.setPhone("555-0001");
//         c1.setAddressLine1("123 Batch St");
//         c1.setCity("Batch City");
//         c1.setCountry("USA");
// 
//         Customer c2 = new Customer();
//         c2.setCustomerName("Batch Corp 2");
//         c2.setContactLastName("Batch2");
//         c2.setContactFirstName("Jane");
//         c2.setPhone("555-0002");
//         c2.setAddressLine1("456 Batch St");
//         c2.setCity("Batch City");
//         c2.setCountry("USA");
// 
//         List<Customer> batchList = List.of(c1, c2);
//         
//         // Get the count before the batch insert
//         long initialCount = customerRepository.countAll();
// 
//         // Act: Save multiple records
//         customerRepository.saveAll(batchList);
// 
//         // Assert: The total count should increase by exactly the size of the batch
//         long countAfterBatch = customerRepository.countAll();
//         assertEquals(initialCount + 2, countAfterBatch, "Count should increase by exactly 2 after batch insert");
//         
//         // Additionally, let's verify we can find them in the database using a query by name
//         // (Note: we didn't specify IDs since they are auto-increment, but we know the names are unique to this test)
//         List<Customer> allCustomers = customerRepository.findAll();
//         long countFound = allCustomers.stream()
//                 .filter(c -> c.getCustomerName().startsWith("Batch Corp"))
//                 .count();
//         assertEquals(2, countFound, "Should find exactly 2 newly inserted batch customers");
//     }
// 
//     @Test
//     void saveAll_ShouldThrowException_WhenRequiredFieldsAreMissingInBatch() {
//         // Arrange: Create one valid and one invalid customer
//         Customer validCustomer = new Customer();
//         validCustomer.setCustomerName("Valid Batch Corp");
//         validCustomer.setContactLastName("Valid");
//         validCustomer.setContactFirstName("Valid");
//         validCustomer.setPhone("123");
//         validCustomer.setAddressLine1("123");
//         validCustomer.setCity("City");
//         validCustomer.setCountry("Country");
// 
//         Customer invalidCustomer = new Customer(); // Missing all required fields
// 
//         List<Customer> batchList = List.of(validCustomer, invalidCustomer);
// 
//         // Act & Assert: The whole batch insert should fail (or throw a RuntimeException wrapping the SQLException)
//         RuntimeException exception = assertThrows(RuntimeException.class, () -> customerRepository.saveAll(batchList));
//         assertTrue(exception.getMessage().contains("Batch insert failed"), "Exception should mention batch insert failure");
//     }
// 
//     @Test
//     void saveAll_ShouldDoNothing_WhenListIsEmpty() {
//         // Arrange
//         long initialCount = customerRepository.countAll();
// 
//         // Act
//         customerRepository.saveAll(List.of());
// 
//         // Assert
//         long currentCount = customerRepository.countAll();
//         assertEquals(initialCount, currentCount, "Count should not change when inserting an empty list");
//     }
// }